# Generated by Django 4.0.1 on 2022-05-25 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=500)),
                ('token_generated_time', models.DateTimeField()),
                ('token_expired_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('access_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelfUserModel',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('belongs_to', models.CharField(max_length=500)),
                ('privilege', models.CharField(choices=[('', ''), ('TechnicalUser', 'TechnicalUser'), ('AdminUser', 'Admin')], max_length=20)),
                ('designation', models.CharField(choices=[('', ''), ('Network Admin', 'Network Admin'), ('Network Technician', 'Network Technician'), ('Server Admin', 'Server Admin'), ('System Admin', 'System Admin'), ('System Engineer', 'System Engineer')], default='', max_length=200)),
                ('level', models.CharField(choices=[('', ''), ('level_1', 'level_1'), ('level_2', 'level_2'), ('level_3', 'level_3'), ('level_4', 'level_4'), ('level_5', 'level_5'), ('level_6', 'level_6'), ('level_7', 'level_7'), ('level_8', 'level_8'), ('level_9', 'level_9'), ('level_10', 'level_10')], default='', max_length=20)),
                ('password', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('token_generated_time', models.DateTimeField(auto_now=True)),
                ('expired_time', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
