# Generated by Django 4.0.1 on 2022-05-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('organization_id', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('method', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=500, unique=True)),
                ('Display_name', models.CharField(max_length=200)),
                ('organization_email', models.EmailField(max_length=200)),
                ('organization_phone_number', models.CharField(max_length=50)),
                ('organization_address', models.CharField(max_length=700)),
                ('organization_country', models.CharField(max_length=100)),
                ('organization_pincode', models.IntegerField()),
                ('organization_document', models.CharField(max_length=500)),
                ('access_key', models.CharField(max_length=100)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
            options={
                'db_table': 'organization_data',
            },
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=35, unique=True)),
                ('branch_name', models.CharField(max_length=300)),
                ('branch_email', models.EmailField(max_length=200)),
                ('branch_phone_number', models.CharField(max_length=50)),
                ('branch_address', models.CharField(max_length=700)),
                ('branch_country', models.CharField(max_length=100)),
                ('branch_pincode', models.IntegerField()),
                ('branch_document', models.CharField(max_length=500)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_datas.organizationmodel')),
            ],
            options={
                'db_table': 'branch_data',
            },
        ),
    ]
