# Generated by Django 4.0.1 on 2022-05-25 11:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_datas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_name', models.CharField(max_length=500, unique=True)),
                ('user_email', models.EmailField(max_length=200, unique=True)),
                ('user_privilege', models.CharField(choices=[('ViewUser', 'ViewUser'), ('Admin', 'Admin')], default='ViewUser', max_length=10)),
                ('user_belongs_to', models.CharField(max_length=500)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('access_key', models.CharField(max_length=100)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_datas.organizationmodel')),
            ],
        ),
    ]
